export { default as Header } from './Header'
export { default as Description } from './Description'
export { default as Footer } from './Footer'
export { default as PriceContainer } from './PriceContainer'
export { default as ImageGallery } from './ImageGallery'
