export default {
  FETCH_FILTERS: 'FETCH_FILTERS',
  FETCH_POSTINGS: 'FETCH_POSTINGS',
  SELECTED_OPERATION: 'SELECTED_OPERATION',
  ADDRESS_SEARCHED: 'ADDRESS_SEARCHED',
  LEAD_MODAL: 'LEAD_MODAL',
  SEND_LEAD: 'SEND_LEAD',
  SET_FAVORITED: 'SET_FAVORITED',
}
